---
name: Template-Plugin-ASCIITable
version: 0.1
author:
  - dakkar <dakkar@tehanutilus.net>
abstract: "Allows you to use Text::ASCIITable in your templates.\n"
license: perl
requires:
  Template: 0
  Text::ASCIITable: 0
build_requires:
  Test::More: 0
provides:
  Template::Plugin::ASCIITable:
    file: lib/Template/Plugin/ASCIITable.pm
    version: 0.1
generated_by: Module::Build version 0.2611
